version: "3"
services:
  app:
    image: wd-image-processor-app
    build: .
    links:
      - wd-server
    environment:
      - WD_BASE_URL=http://wd-server:9515
      - PROCESSORS_CONFIG_PATH=/app/processors/processors.json
    ports:
      - 8080:8080
    volumes:
      - ./sampleProcessors:/app/processors
  wd-server:
    image: quay.io/wakaba/chromedriver:stable
    command: /cd
    ports:
      - 10000:9515
